version: '3.8'

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attacker
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./data:/root/data
    networks:
      - pentest_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: victim
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - pentest_network
    command: /bin/bash -c "/bin/services.sh && bash"

networks:
  pentest_network:
    driver: bridge